/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/sample": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getVersion_1"];
        put?: never;
        post: operations["getRequestBody"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sample/error/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["getError"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/files/upload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 파일 업로드
         * @description 단일 파일을 업로드합니다.
         */
        post: operations["uploadFile"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/brand": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 브랜드 목록조회 */
        get: operations["getBrandList"];
        put?: never;
        /** 브랜드 기본정보 전환 등록 */
        post: operations["conversionRegistration"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/brand/{brandId}/middle-category": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 브랜드 중분류 등록 */
        post: operations["createMiddleCategory"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/app/icon": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 앱런쳐아이콘 조회 */
        get: operations["getBrandAppLauncherIcon"];
        put?: never;
        /** 앱런쳐아이콘 등록 */
        post: operations["createAppLauncherIcon"];
        delete?: never;
        options?: never;
        head?: never;
        /** 앱런쳐아이콘 수정 */
        patch: operations["updateAppLauncherIcon"];
        trace?: never;
    };
    "/admin/user/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 외식업 관리자 등록 */
        post: operations["registerOesikupAdmin"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/brand/{brandId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 브랜드 상세보기 */
        get: operations["getBrandDetail"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** 브랜드 기본정보 수정 */
        patch: operations["updateBrandBasicInfo"];
        trace?: never;
    };
    "/brand/middle-category/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 브랜드 중분류 조회 */
        get: operations["getBrandMiddleCategory"];
        put?: never;
        post?: never;
        /** 브랜드 중분류 삭제 */
        delete: operations["deleteBrandMiddleCategory"];
        options?: never;
        head?: never;
        /** 브랜드 중분류 수정 */
        patch: operations["updateBrandMiddleCategory"];
        trace?: never;
    };
    "/admin/user/update": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** 외식업 관리자 수정 */
        patch: operations["updateOesikupAdmin"];
        trace?: never;
    };
    "/version": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getVersion"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/store/manager": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 매장관리자 목록조회 */
        get: operations["findStoreManagers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sample/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getPathVariable"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sample/{id}/param": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getRequestParam"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sample/mybatis/{input}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getSampleText"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/common/health-check": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["healthCheck"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/brand/{brandId}/convertible-middle-category": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 전환가능 브랜드 중분류 검색 */
        get: operations["getConvertibleBrandMiddleCategories"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/brand/convertible": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 전환가능 브랜드 검색 */
        get: operations["findConvertibleBrand"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/app/icon/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 앱런쳐아이콘 조회 */
        get: operations["getBrandAppLauncherIcon_1"];
        put?: never;
        post?: never;
        /** 앱런쳐아이콘 삭제 */
        delete: operations["deleteAppLauncherIcon"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/user": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 외식업 유저 검색 */
        get: operations["findOesikupAdminUser"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/user/fresh-on-user": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 프레시온 유저 검색 */
        get: operations["findFreshOnUser"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        VersionInfo: {
            hostname: string;
            startedAt: string;
            timezone: string;
            echoParam?: string;
        };
        CaribbeanException: {
            code: string;
            /** @enum {string} */
            httpStatus: "100 CONTINUE" | "101 SWITCHING_PROTOCOLS" | "102 PROCESSING" | "103 EARLY_HINTS" | "103 CHECKPOINT" | "200 OK" | "201 CREATED" | "202 ACCEPTED" | "203 NON_AUTHORITATIVE_INFORMATION" | "204 NO_CONTENT" | "205 RESET_CONTENT" | "206 PARTIAL_CONTENT" | "207 MULTI_STATUS" | "208 ALREADY_REPORTED" | "226 IM_USED" | "300 MULTIPLE_CHOICES" | "301 MOVED_PERMANENTLY" | "302 FOUND" | "302 MOVED_TEMPORARILY" | "303 SEE_OTHER" | "304 NOT_MODIFIED" | "305 USE_PROXY" | "307 TEMPORARY_REDIRECT" | "308 PERMANENT_REDIRECT" | "400 BAD_REQUEST" | "401 UNAUTHORIZED" | "402 PAYMENT_REQUIRED" | "403 FORBIDDEN" | "404 NOT_FOUND" | "405 METHOD_NOT_ALLOWED" | "406 NOT_ACCEPTABLE" | "407 PROXY_AUTHENTICATION_REQUIRED" | "408 REQUEST_TIMEOUT" | "409 CONFLICT" | "410 GONE" | "411 LENGTH_REQUIRED" | "412 PRECONDITION_FAILED" | "413 PAYLOAD_TOO_LARGE" | "413 REQUEST_ENTITY_TOO_LARGE" | "414 URI_TOO_LONG" | "414 REQUEST_URI_TOO_LONG" | "415 UNSUPPORTED_MEDIA_TYPE" | "416 REQUESTED_RANGE_NOT_SATISFIABLE" | "417 EXPECTATION_FAILED" | "418 I_AM_A_TEAPOT" | "419 INSUFFICIENT_SPACE_ON_RESOURCE" | "420 METHOD_FAILURE" | "421 DESTINATION_LOCKED" | "422 UNPROCESSABLE_ENTITY" | "423 LOCKED" | "424 FAILED_DEPENDENCY" | "425 TOO_EARLY" | "426 UPGRADE_REQUIRED" | "428 PRECONDITION_REQUIRED" | "429 TOO_MANY_REQUESTS" | "431 REQUEST_HEADER_FIELDS_TOO_LARGE" | "451 UNAVAILABLE_FOR_LEGAL_REASONS" | "500 INTERNAL_SERVER_ERROR" | "501 NOT_IMPLEMENTED" | "502 BAD_GATEWAY" | "503 SERVICE_UNAVAILABLE" | "504 GATEWAY_TIMEOUT" | "505 HTTP_VERSION_NOT_SUPPORTED" | "506 VARIANT_ALSO_NEGOTIATES" | "507 INSUFFICIENT_STORAGE" | "508 LOOP_DETECTED" | "509 BANDWIDTH_LIMIT_EXCEEDED" | "510 NOT_EXTENDED" | "511 NETWORK_AUTHENTICATION_REQUIRED";
            message: string;
            additionalMessage?: string;
            details: string[];
            cause?: {
                stackTrace?: {
                    classLoaderName?: string;
                    moduleName?: string;
                    moduleVersion?: string;
                    methodName?: string;
                    fileName?: string;
                    /** Format: int32 */
                    lineNumber?: number;
                    className?: string;
                    nativeMethod?: boolean;
                }[];
                message?: string;
                localizedMessage?: string;
            };
            stackTrace?: {
                classLoaderName?: string;
                moduleName?: string;
                moduleVersion?: string;
                methodName?: string;
                fileName?: string;
                /** Format: int32 */
                lineNumber?: number;
                className?: string;
                nativeMethod?: boolean;
            }[];
            suppressed?: {
                stackTrace?: {
                    classLoaderName?: string;
                    moduleName?: string;
                    moduleVersion?: string;
                    methodName?: string;
                    fileName?: string;
                    /** Format: int32 */
                    lineNumber?: number;
                    className?: string;
                    nativeMethod?: boolean;
                }[];
                message?: string;
                localizedMessage?: string;
            }[];
            localizedMessage?: string;
        };
        /** @description 파일 업로드 명령 DTO */
        "FileUploadCommandDto.Result": {
            /** Format: int64 */
            sysAttachInfoSeqId: number;
            fileUri: string;
        };
        /** @description 브랜드 등록 DTO */
        "BrandDto.CreateCommand": {
            /**
             * @description 브랜드명
             * @example MyBrand
             */
            brandName: string;
            /**
             * @description 본사고객코드-대분류
             * @example HCC456
             */
            largeGbn: string;
            /**
             * @description 본점고객코드
             * @example HCC456
             */
            upperEstCd: string;
            /**
             * Format: date-time
             * @description 오픈일시
             */
            openDateTime: string;
            /**
             * Format: date-time
             * @description 전화번호 수집 기간 시작
             */
            phoneCollectionDateTimeStart?: string;
            /**
             * Format: date-time
             * @description 전화번호 수집 기간 종료
             */
            phoneCollectionDateTimeEnd?: string;
            /**
             * @description 브랜드 path
             * @example /@brand
             */
            brandPath?: string;
            /**
             * @description 서비스 사용유무
             * @example Y
             * @enum {string}
             */
            serviceYn: "Y" | "N";
        };
        /** @description 브랜드 등록결과 DTO */
        "BrandDto.CreateResult": {
            /**
             * Format: int64
             * @description 등록된 brand 의 식별 아이디
             */
            brandId: number;
            /** @description 일괄등록된 매장관리자 전화번호 리스트 */
            storeManagerBatchInsertResult: components["schemas"]["BrandDto.CreateResultBrandStoreManagerInfo"][];
        };
        /** @description 매장관리자 전화번호 정보 */
        "BrandDto.CreateResultBrandStoreManagerInfo": {
            /** @description 매장코드 */
            estCd: string;
            /** @description 폰번호 */
            phone: string;
            /** @description 이름 */
            userName?: string;
        };
        BrandMiddleCategoryCreateCommand: {
            /**
             * @description 브랜드 중분류 middle 아이디
             * @example 1
             */
            middleGbn: string;
            /**
             * @description 브랜드 이름
             * @example 브랜드
             */
            brandName?: string;
            /**
             * @description 브랜드 중분류 path
             * @example f
             */
            brandPath?: string;
            /**
             * Format: int64
             * @description 브랜드 중분류 pcLogoAttachSeqId
             * @example 12
             */
            pcLogoAttachSeqId?: number;
            /**
             * Format: int64
             * @description 브랜드 중분류 모바일 로고 AttachSeqId
             * @example 12
             */
            mobileLogoAttachSeqId?: number;
            /**
             * Format: int64
             * @description 브랜드 중분류 favicon AttachSeqId
             * @example 12
             */
            faviconAttachSeqId?: number;
            /**
             * @description 브랜드 중분류 피씨 백그라운드 컬러
             * @example #ffffff
             */
            pcBackgroundColor?: string;
            /**
             * @description 브랜드 중분류 모바일 백그라운드 컬러
             * @example #ffffff
             */
            mobileBackgroundColor?: string;
            /**
             * @description 브랜드 중분류 앱 런쳐아이콘 키
             * @example FC_APP_ICON_S12313
             */
            appLauncherIconKey?: string;
            /**
             * @description brand_path 대분류와 동일
             * @example Y
             * @enum {string}
             */
            sameHeadquarterPathYn: "Y" | "N";
        };
        /** @description 앱 아이콘 등록 DTO */
        "AppIconDto.CreateCommand": {
            headquarterAppLauncherIconKey: string;
            /** Format: int64 */
            iconAttachSeqId: number;
        };
        /** @description 외식업 관리자 등록 DTO */
        "AdminUserDto.CreateCommand": {
            /** @description 유저아이디 */
            username: string;
        };
        /** @description 브랜드 수정 DTO  */
        "BrandDto.UpdateCommand": {
            /**
             * @description 브랜드명
             * @example MyBrand
             */
            brandName: string;
            /**
             * Format: date-time
             * @description 오픈일시
             */
            openDateTime: string;
            /**
             * @description 사용유무
             * @example 2023-01-01T10:00:00
             * @enum {string}
             */
            serviceYn: "Y" | "N";
            /**
             * Format: date-time
             * @description 전화번호 수집 기간 시작
             */
            phoneCollectionDateTimeStart?: string;
            /**
             * Format: date-time
             * @description 전화번호 수집 기간 종료
             */
            phoneCollectionDateTimeEnd?: string;
            /**
             * Format: int64
             * @description pc 브랜드 로고 seq id. null 인경우 null 로 업데이트
             * @example 1
             */
            pcBrandLogoSeqId?: number | null;
            /**
             * Format: int64
             * @description 모바일 브랜드 로고 seq id. null 인경우 null 로 업데이트
             * @example 1
             */
            mobileBrandLogoSeqId?: number | null;
            /**
             * Format: int64
             * @description 파비콘 브랜드 로고 seq id. null 인경우 null 로 업데이트
             * @example 1
             */
            faviconSeqId?: number | null;
            /**
             * @description 앱런쳐 아이콘 키. null 인경우 null 로 업데이트
             * @example FC_APP_ICON
             */
            appLauncherIconKey?: string | null;
            /**
             * @description 브랜드 path. null 인경우 수정되지 않음
             * @example /@brand
             */
            brandPath?: string;
            /**
             * @description 모바일 배경컬러
             * @example #FFFFFF
             */
            mobileBgColor?: string;
            /**
             * @description pc 배경컬러
             * @example #FFFFFF
             */
            pcBgColor?: string;
        };
        /** @description 브랜드 수정결과 DTO */
        "BrandDto.UpdateResult": {
            /**
             * Format: int64
             * @description 업데이트된 brand 의 식별 아이디
             */
            brandId: number;
        };
        BrandMiddleCategoryUpdateCommand: {
            /**
             * @description 브랜드 이름
             * @example 브랜드
             */
            brandName?: string;
            /**
             * @description 브랜드 중분류 path
             * @example f
             */
            brandPath?: string;
            /**
             * Format: int64
             * @description 브랜드 중분류 pcLogoAttachSeqId
             * @example 12
             */
            pcLogoAttachSeqId?: number;
            /**
             * Format: int64
             * @description 브랜드 중분류 모바일 로고 AttachSeqId
             * @example 12
             */
            mobileLogoAttachSeqId?: number;
            /**
             * Format: int64
             * @description 브랜드 중분류 favicon AttachSeqId
             * @example 12
             */
            faviconAttachSeqId?: number;
            /**
             * @description 브랜드 중분류 피씨 백그라운드 컬러
             * @example #ffffff
             */
            pcBackgroundColor?: string;
            /**
             * @description 브랜드 중분류 모바일 백그라운드 컬러
             * @example #ffffff
             */
            mobileBackgroundColor?: string;
            /**
             * @description 브랜드 중분류 앱 런쳐아이콘 키
             * @example FC_APP_ICON_S12313
             */
            appLauncherIconKey?: string;
            /**
             * @description brand_path 대분류와 동일
             * @example Y
             * @enum {string}
             */
            sameHeadquarterPathYn: "Y" | "N";
        };
        /** @description 앱 아이콘 수정 DTO */
        "AppIconDto.UpdateCommand": {
            /** Format: int64 */
            id: number;
            /** Format: int64 */
            iconAttachSeqId: number;
        };
        /** @description 외식업 관리자 수정 DTO */
        "AdminUserDto.UpdateCommand": {
            /** @description 유저아이디 */
            username: string;
            /**
             * @description 사용유무
             * @enum {string}
             */
            useYn: "Y" | "N";
        };
        "PageResponseStoreManagerQueryDto.Result": {
            items: components["schemas"]["StoreManagerQueryDto.Result"][];
            pagination: components["schemas"]["PaginationStoreManagerQueryDto.Result"];
        };
        "PaginationStoreManagerQueryDto.Result": {
            /**
             * Format: int32
             * @description 페이지 번호
             */
            page: number;
            /**
             * Format: int32
             * @description 페이지 크기
             */
            pageSize: number;
            /**
             * Format: int32
             * @description 총 개수
             */
            totalCount: number;
            /** @description 마지막 페이지 여부 */
            isLast: boolean;
            /**
             * Format: int32
             * @description 총 페이지 수
             */
            totalPage: number;
        };
        /** @description 매장관리자 조회 결과 DTO */
        "StoreManagerQueryDto.Result": {
            /**
             * Format: int64
             * @description 매장관리자 PK
             */
            fcUserInfoId: number;
            /** @description 매장코드 */
            estCd: string;
            /** @description 전화번호 */
            phone: string;
            /** @description 본점매장코드 */
            upperEstCd?: string;
            /** @description 이름 */
            userName?: string;
            /**
             * Format: date-time
             * @description 생성일시
             */
            createDate?: string;
            /**
             * Format: date-time
             * @description 수정일시
             */
            updateDate?: string;
            /** @description 생성자 */
            createUserId?: string;
            /** @description 수정자 */
            updateUserId?: string;
            /** @description 배치일괄등록 여부 */
            batchInsertYn?: string;
            /** @description 배치로 등록된경우, 원본 전화번호 */
            originPhoneNumber?: string;
            /** @description 브랜드명 */
            brandName?: string;
            /** @description 매장명 */
            storeName?: string;
        };
        /** @description 브랜드 목록 정보를 나타내는 DTO */
        "BrandDto.Result": {
            /**
             * Format: int64
             * @description 식별번호
             */
            brandId: number;
            /**
             * @description 브랜드명
             * @example MyBrand
             */
            brandName: string;
            /**
             * @description 본사고객코드
             * @example HCC456
             */
            headOfficeCustomerCode: string;
            /**
             * @description 대분류
             * @example Fashion
             */
            largeCategory: string;
            /**
             * @description 중분류
             * @example Clothing
             */
            middleCategory: string;
            /**
             * @description 서비스대상여부
             * @example Y/N
             */
            serviceYn: string;
            /**
             * Format: date-time
             * @description 오픈일시
             */
            openDateTime: string;
            /**
             * @description 전화번호 수집 대상
             * @example https://www.example.com/brand/logo.png
             */
            phoneNumberCollectionYn: string;
            /**
             * Format: int64
             * @description PC 브랜드로고 seq id
             * @example 1
             */
            pcBrandLogoSeqId?: number;
            /**
             * @description PC 브랜드로고 uri
             * @example https://www.example.com/brand/logo.png
             */
            pcBrandLogoUri?: string;
            /**
             * Format: int64
             * @description 모바일 브랜드로고 seq id
             * @example 1
             */
            mobileBrandLogoSeqId?: number;
            /**
             * @description 모바일 브랜드로고 uri
             * @example https://www.example.com/brand/logo.png
             */
            mobileBrandLogoUri?: string;
            /**
             * Format: int64
             * @description 파비콘 seq id
             * @example 1
             */
            faviconSeqId?: number;
            /**
             * @description 파비콘 uri
             * @example https://www.example.com/brand/logo.png
             */
            faviconUri?: string;
            /**
             * @description 앱런쳐 아이콘 키
             * @example FC_APP_ICON
             */
            appLauncherIconKey?: string;
            /**
             * @description 브랜드 경로
             * @example /@brand
             */
            brandPath?: string;
        };
        "PageResponseBrandDto.Result": {
            items: components["schemas"]["BrandDto.Result"][];
            pagination: components["schemas"]["PaginationBrandDto.Result"];
        };
        "PaginationBrandDto.Result": {
            /**
             * Format: int32
             * @description 페이지 번호
             */
            page: number;
            /**
             * Format: int32
             * @description 페이지 크기
             */
            pageSize: number;
            /**
             * Format: int32
             * @description 총 개수
             */
            totalCount: number;
            /** @description 마지막 페이지 여부 */
            isLast: boolean;
            /**
             * Format: int32
             * @description 총 페이지 수
             */
            totalPage: number;
        };
        /** @description 브랜드 정보를 나타내는 DTO */
        "BrandDetailDto.Result": {
            /**
             * Format: int64
             * @description 식별번호
             */
            brandId: number;
            /**
             * @description 브랜드명
             * @example MyBrand
             */
            brandName: string;
            /**
             * @description 본사고객코드
             * @example HCC456
             */
            headOfficeCustomerCode: string;
            /**
             * @description 대분류
             * @example Fashion
             */
            largeCategory: string;
            /**
             * @description 중분류
             * @example Clothing
             */
            middleCategory: string;
            /**
             * @description 서비스대상여부
             * @example Y/N
             */
            serviceYn: string;
            /**
             * Format: date-time
             * @description 오픈일시
             */
            openDateTime: string;
            /**
             * @description 전화번호 수집 대상
             * @example Y/N
             */
            phoneNumberCollectionYn: string;
            /**
             * Format: date-time
             * @description 전화번호 수집 기간 시작시간
             */
            collectionStartDateTime?: string;
            /**
             * Format: date-time
             * @description 전화번호 수집 기간 종료시간
             */
            collectionEndDateTime?: string;
            /**
             * Format: int64
             * @description PC 브랜드로고 seq id
             * @example 1
             */
            pcBrandLogoSeqId?: number;
            /**
             * @description 로고관리-브랜드로고(PC)
             * @example https://upload.oesikup.com/brand-identity/s97687/6/s97687_icon.jpg
             */
            pcBrandLogoUri?: string;
            /**
             * Format: int64
             * @description 모바일 브랜드로고 seq id
             * @example 1
             */
            mobileBrandLogoSeqId?: number;
            /**
             * @description 로고관리-브랜드로고(모바일)
             * @example https://upload.oesikup.com/brand-identity/s97687/6/s97687_icon.jpg
             */
            mobileBrandLogoUri?: string;
            /**
             * Format: int64
             * @description 파비콘 seq id
             * @example 1
             */
            faviconSeqId?: number;
            /**
             * @description 로고관리-파비콘
             * @example https://upload.oesikup.com/brand-identity/s97687/6/s97687_icon.jpg
             */
            faviconUri?: string;
            /**
             * @description 로고관리 - BG Color
             * @example #FF00AAFF
             */
            pcBgColor?: string;
            /**
             * @description 로고관리 - BG Color
             * @example #FF00AAFF
             */
            mobileBgColor?: string;
            /**
             * @description 앱런쳐 아이콘 식별 키값
             * @example FC_APP_ICON_DEFAULT
             */
            appLauncherIconKey?: string;
            /**
             * @description 브랜드 경로
             * @example /@brand
             */
            brandPath?: string;
            /** @description 브랜드 중분류 키 리스트 */
            brandMiddleCategories: components["schemas"]["BrandMiddleCategoryKeyInfo"][];
        };
        /** @description 브랜드 중분류 키 정보 */
        BrandMiddleCategoryKeyInfo: {
            /**
             * Format: int64
             * @description 브랜드 중분류 ID
             * @example 1
             */
            headquarterBrandInfoId: number;
            /**
             * @description 브랜드 이름
             * @example 브랜드
             */
            brandName: string;
            /**
             * Format: int64
             * @description 지점 매장수
             * @example 1
             */
            storeCount: number;
            /**
             * @description 중분류코드
             * @example S11233
             */
            middleGbn: string;
        };
        /** @description 전환가능 브랜드 정보를 나타내는 DTO */
        "ConvertibleBrandDto.Result": {
            /**
             * @description 식별번호
             * @example B123
             */
            estCd: string;
            /**
             * @description 매장이름
             * @example 매장이름
             */
            estName?: string;
            /**
             * @description 본점매장코드
             * @example S0001
             */
            upperEstCd?: string;
            /**
             * @description 본점매장 코드 대분류
             * @example S0001
             */
            largeGbn?: string;
            /**
             * @description 본점매장 코드 중분류
             * @example S0001
             */
            middleGbn?: string;
            /**
             * @description 본점매장 코드 소분류
             * @example S0001
             */
            smallGbn?: string;
            /**
             * Format: int32
             * @description 매장수
             * @example 10
             */
            storeCount?: number;
        };
        "PageResponseConvertibleBrandDto.Result": {
            items: components["schemas"]["ConvertibleBrandDto.Result"][];
            pagination: components["schemas"]["PaginationConvertibleBrandDto.Result"];
        };
        "PaginationConvertibleBrandDto.Result": {
            /**
             * Format: int32
             * @description 페이지 번호
             */
            page: number;
            /**
             * Format: int32
             * @description 페이지 크기
             */
            pageSize: number;
            /**
             * Format: int32
             * @description 총 개수
             */
            totalCount: number;
            /** @description 마지막 페이지 여부 */
            isLast: boolean;
            /**
             * Format: int32
             * @description 총 페이지 수
             */
            totalPage: number;
        };
        /** @description 브랜드 중분류 정보 */
        BrandMiddleCategoryDto: {
            /**
             * Format: int64
             * @description 브랜드 중분류 ID
             * @example 1
             */
            headquarterBrandInfoId: number;
            /**
             * Format: int64
             * @description 브랜드 ID
             * @example 1
             */
            headquarterInfoId: number;
            /**
             * @description 브랜드 이름
             * @example 브랜드
             */
            brandName?: string;
            /**
             * @description 브랜드 중분류 path
             * @example f
             */
            brandPath?: string;
            /**
             * Format: int64
             * @description 브랜드 중분류 pcLogoAttachSeqId
             * @example 12
             */
            pcLogoAttachSeqId?: number;
            /**
             * @description 브랜드 중분류 피씨 로고 URI
             * @example https://example.com/logo.png
             */
            pcBrandLogoUri?: string;
            /**
             * Format: int64
             * @description 브랜드 중분류 모바일 로고 AttachSeqId
             * @example 12
             */
            mobileLogoAttachSeqId?: number;
            /**
             * @description 브랜드 중분류 모바일 로고 URI
             * @example https://example.com/logo.png
             */
            mobileBrandLogoUri?: string;
            /**
             * Format: int64
             * @description 브랜드 중분류 favicon AttachSeqId
             * @example 12
             */
            faviconAttachSeqId?: number;
            /**
             * @description 브랜드 중분류 favicon URI
             * @example https://example.com/favicon.ico
             */
            faviconUri?: string;
            /**
             * @description 브랜드 중분류 피씨 백그라운드 컬러
             * @example #ffffff
             */
            pcBackgroundColor?: string;
            /**
             * @description 브랜드 중분류 모바일 백그라운드 컬러
             * @example #ffffff
             */
            mobileBackgroundColor?: string;
            /**
             * @description 브랜드 중분류 앱 런쳐아이콘 키
             * @example FC_APP_ICON_S12313
             */
            appLauncherIconKey?: string;
            /**
             * Format: date-time
             * @description 생성시간
             */
            createDate?: string;
            /**
             * Format: date-time
             * @description 수정시간
             */
            updateDate?: string;
            /**
             * @description 생성유저아이디
             * @example aaa
             */
            createUserId?: string;
            /**
             * @description 수정유저아이디
             * @example aaaa
             */
            updateUserId?: string;
            /**
             * Format: int64
             * @description 지점 매장수
             * @example 1
             */
            storeCount: number;
            /**
             * @description brand_path 대분류와 동일
             * @example Y
             * @enum {string}
             */
            sameHeadquarterPathYn: "Y" | "N";
        };
        "AppIconDto.Result": {
            /** Format: int64 */
            id: number;
            headquarterAppLauncherIconKey: string;
            /** Format: int64 */
            iconAttachSeqId?: number;
            thumbnailUri?: string;
            /** @enum {string} */
            appDistributionYn: "Y" | "N";
            /** Format: date-time */
            createDate: string;
            /** Format: date-time */
            updateDate: string;
            createUserId?: string;
            updateUserId?: string;
        };
        "PageResponseAppIconDto.Result": {
            items: components["schemas"]["AppIconDto.Result"][];
            pagination: components["schemas"]["PaginationAppIconDto.Result"];
        };
        "PaginationAppIconDto.Result": {
            /**
             * Format: int32
             * @description 페이지 번호
             */
            page: number;
            /**
             * Format: int32
             * @description 페이지 크기
             */
            pageSize: number;
            /**
             * Format: int32
             * @description 총 개수
             */
            totalCount: number;
            /** @description 마지막 페이지 여부 */
            isLast: boolean;
            /**
             * Format: int32
             * @description 총 페이지 수
             */
            totalPage: number;
        };
        /** @description 외식업 관리자 검색 결과 */
        "AdminUserDto.Result": {
            /** Format: int64 */
            id: number;
            userName: string;
            name?: string;
            createUserId?: string;
            updateUserid?: string;
            /** Format: date-time */
            createDate?: string;
            /** Format: date-time */
            updateDate?: string;
            useYn: string;
        };
        "PageResponseAdminUserDto.Result": {
            items: components["schemas"]["AdminUserDto.Result"][];
            pagination: components["schemas"]["PaginationAdminUserDto.Result"];
        };
        "PaginationAdminUserDto.Result": {
            /**
             * Format: int32
             * @description 페이지 번호
             */
            page: number;
            /**
             * Format: int32
             * @description 페이지 크기
             */
            pageSize: number;
            /**
             * Format: int32
             * @description 총 개수
             */
            totalCount: number;
            /** @description 마지막 페이지 여부 */
            isLast: boolean;
            /**
             * Format: int32
             * @description 총 페이지 수
             */
            totalPage: number;
        };
        "FreshOnUserDto.Result": {
            userId?: string;
            userName?: string;
        };
        "PageResponseFreshOnUserDto.Result": {
            items: components["schemas"]["FreshOnUserDto.Result"][];
            pagination: components["schemas"]["PaginationFreshOnUserDto.Result"];
        };
        "PaginationFreshOnUserDto.Result": {
            /**
             * Format: int32
             * @description 페이지 번호
             */
            page: number;
            /**
             * Format: int32
             * @description 페이지 크기
             */
            pageSize: number;
            /**
             * Format: int32
             * @description 총 개수
             */
            totalCount: number;
            /** @description 마지막 페이지 여부 */
            isLast: boolean;
            /**
             * Format: int32
             * @description 총 페이지 수
             */
            totalPage: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getVersion_1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VersionInfo"];
                };
            };
        };
    };
    getRequestBody: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["VersionInfo"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VersionInfo"];
                };
            };
        };
    };
    getError: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description 에러를 조회하기 위한 ID
                 * @example 123
                 */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 성공적으로 조회됨 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VersionInfo"];
                };
            };
            /** @description 잘못된 요청 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CaribbeanException"];
                };
            };
            /** @description 서버 내부 오류 */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CaribbeanException"];
                };
            };
        };
    };
    uploadFile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "multipart/form-data": {
                    /** Format: binary */
                    file: string;
                };
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FileUploadCommandDto.Result"];
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example USER_NOT_FOUND */
                        code?: string;
                        /** @example null */
                        details?: Record<string, never>;
                        /** @example null */
                        httpStatus?: Record<string, never>;
                        /** @example The user was not found. */
                        message?: string;
                    };
                };
            };
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example USER_NOT_FOUND */
                        code?: string;
                        /** @example null */
                        details?: Record<string, never>;
                        /** @example null */
                        httpStatus?: Record<string, never>;
                        /** @example The user was not found. */
                        message?: string;
                    };
                };
            };
        };
    };
    getBrandList: {
        parameters: {
            query?: {
                /**
                 * @description 페이지 번호 (기본값: 1)
                 * @example 1
                 */
                page?: number;
                /**
                 * @description 페이지 크기 (기본값: 10)
                 * @example 10
                 */
                pageSize?: number;
                /**
                 * @description 브랜드명
                 * @example 브랜드명
                 */
                brandName?: string;
                /**
                 * @description 본사고객코드-대분류
                 * @example S0001
                 */
                headOfficeCustomerCodeLargeCategory?: string;
                /**
                 * @description 본사고객코드-중분류
                 * @example S0001
                 */
                headOfficeCustomerCodeMiddleCategory?: string;
                /**
                 * @description 오픈일시 시작 (기본값: 현재시간)
                 * @example 2025-01-01
                 */
                openDateStart?: string;
                /**
                 * @description 오픈일시 종료 (기본값: 2999-12-31)
                 * @example 2999-12-31
                 */
                openDateEnd?: string;
                /**
                 * @description 서비스대상 (Y/N/ALL 기본값: 'ALL')
                 * @example ALL
                 */
                serviceTarget?: "ALL" | "Y" | "N";
                /**
                 * @description 전화번호 수집대상 (Y/N/ALL 기본값: 'ALL')
                 * @example ALL
                 */
                phoneCollectTarget?: "ALL" | "Y" | "N";
                /**
                 * @description 웹(PC) 로고 등록여부 (Y/N/ALL 기본값: 'ALL')
                 * @example ALL
                 */
                pcLogoRegistered?: "ALL" | "Y" | "N";
                /**
                 * @description 모바일 로고 등록여부 (Y/N/ALL 기본값: 'ALL')
                 * @example ALL
                 */
                mobileLogoRegistered?: "ALL" | "Y" | "N";
                /**
                 * @description 파비콘 등록여부 (Y/N/ALL 기본값: 'ALL')
                 * @example ALL
                 */
                faviconRegistered?: "ALL" | "Y" | "N";
                /**
                 * @description 모바일 앱 런쳐아이콘 등록여부 (Y/N/ALL 기본값: 'ALL')
                 * @example ALL
                 */
                appLauncherIconRegistered?: "ALL" | "Y" | "N";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PageResponseBrandDto.Result"];
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example USER_NOT_FOUND */
                        code?: string;
                        /** @example null */
                        details?: Record<string, never>;
                        /** @example null */
                        httpStatus?: Record<string, never>;
                        /** @example The user was not found. */
                        message?: string;
                    };
                };
            };
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example USER_NOT_FOUND */
                        code?: string;
                        /** @example null */
                        details?: Record<string, never>;
                        /** @example null */
                        httpStatus?: Record<string, never>;
                        /** @example The user was not found. */
                        message?: string;
                    };
                };
            };
        };
    };
    conversionRegistration: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BrandDto.CreateCommand"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BrandDto.CreateResult"];
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example USER_NOT_FOUND */
                        code?: string;
                        /** @example null */
                        details?: Record<string, never>;
                        /** @example null */
                        httpStatus?: Record<string, never>;
                        /** @example The user was not found. */
                        message?: string;
                    };
                };
            };
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example USER_NOT_FOUND */
                        code?: string;
                        /** @example null */
                        details?: Record<string, never>;
                        /** @example null */
                        httpStatus?: Record<string, never>;
                        /** @example The user was not found. */
                        message?: string;
                    };
                };
            };
        };
    };
    createMiddleCategory: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                brandId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BrandMiddleCategoryCreateCommand"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example USER_NOT_FOUND */
                        code?: string;
                        /** @example null */
                        details?: Record<string, never>;
                        /** @example null */
                        httpStatus?: Record<string, never>;
                        /** @example The user was not found. */
                        message?: string;
                    };
                };
            };
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example USER_NOT_FOUND */
                        code?: string;
                        /** @example null */
                        details?: Record<string, never>;
                        /** @example null */
                        httpStatus?: Record<string, never>;
                        /** @example The user was not found. */
                        message?: string;
                    };
                };
            };
        };
    };
    getBrandAppLauncherIcon: {
        parameters: {
            query?: {
                keyword?: string;
                page?: number;
                pageSize?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PageResponseAppIconDto.Result"];
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example USER_NOT_FOUND */
                        code?: string;
                        /** @example null */
                        details?: Record<string, never>;
                        /** @example null */
                        httpStatus?: Record<string, never>;
                        /** @example The user was not found. */
                        message?: string;
                    };
                };
            };
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example USER_NOT_FOUND */
                        code?: string;
                        /** @example null */
                        details?: Record<string, never>;
                        /** @example null */
                        httpStatus?: Record<string, never>;
                        /** @example The user was not found. */
                        message?: string;
                    };
                };
            };
        };
    };
    createAppLauncherIcon: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AppIconDto.CreateCommand"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": number;
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example USER_NOT_FOUND */
                        code?: string;
                        /** @example null */
                        details?: Record<string, never>;
                        /** @example null */
                        httpStatus?: Record<string, never>;
                        /** @example The user was not found. */
                        message?: string;
                    };
                };
            };
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example USER_NOT_FOUND */
                        code?: string;
                        /** @example null */
                        details?: Record<string, never>;
                        /** @example null */
                        httpStatus?: Record<string, never>;
                        /** @example The user was not found. */
                        message?: string;
                    };
                };
            };
        };
    };
    updateAppLauncherIcon: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AppIconDto.UpdateCommand"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": number;
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example USER_NOT_FOUND */
                        code?: string;
                        /** @example null */
                        details?: Record<string, never>;
                        /** @example null */
                        httpStatus?: Record<string, never>;
                        /** @example The user was not found. */
                        message?: string;
                    };
                };
            };
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example USER_NOT_FOUND */
                        code?: string;
                        /** @example null */
                        details?: Record<string, never>;
                        /** @example null */
                        httpStatus?: Record<string, never>;
                        /** @example The user was not found. */
                        message?: string;
                    };
                };
            };
        };
    };
    registerOesikupAdmin: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AdminUserDto.CreateCommand"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example USER_NOT_FOUND */
                        code?: string;
                        /** @example null */
                        details?: Record<string, never>;
                        /** @example null */
                        httpStatus?: Record<string, never>;
                        /** @example The user was not found. */
                        message?: string;
                    };
                };
            };
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example USER_NOT_FOUND */
                        code?: string;
                        /** @example null */
                        details?: Record<string, never>;
                        /** @example null */
                        httpStatus?: Record<string, never>;
                        /** @example The user was not found. */
                        message?: string;
                    };
                };
            };
        };
    };
    getBrandDetail: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                brandId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BrandDetailDto.Result"];
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example USER_NOT_FOUND */
                        code?: string;
                        /** @example null */
                        details?: Record<string, never>;
                        /** @example null */
                        httpStatus?: Record<string, never>;
                        /** @example The user was not found. */
                        message?: string;
                    };
                };
            };
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example USER_NOT_FOUND */
                        code?: string;
                        /** @example null */
                        details?: Record<string, never>;
                        /** @example null */
                        httpStatus?: Record<string, never>;
                        /** @example The user was not found. */
                        message?: string;
                    };
                };
            };
        };
    };
    updateBrandBasicInfo: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                brandId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BrandDto.UpdateCommand"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BrandDto.UpdateResult"];
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example USER_NOT_FOUND */
                        code?: string;
                        /** @example null */
                        details?: Record<string, never>;
                        /** @example null */
                        httpStatus?: Record<string, never>;
                        /** @example The user was not found. */
                        message?: string;
                    };
                };
            };
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example USER_NOT_FOUND */
                        code?: string;
                        /** @example null */
                        details?: Record<string, never>;
                        /** @example null */
                        httpStatus?: Record<string, never>;
                        /** @example The user was not found. */
                        message?: string;
                    };
                };
            };
        };
    };
    getBrandMiddleCategory: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BrandMiddleCategoryDto"];
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example USER_NOT_FOUND */
                        code?: string;
                        /** @example null */
                        details?: Record<string, never>;
                        /** @example null */
                        httpStatus?: Record<string, never>;
                        /** @example The user was not found. */
                        message?: string;
                    };
                };
            };
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example USER_NOT_FOUND */
                        code?: string;
                        /** @example null */
                        details?: Record<string, never>;
                        /** @example null */
                        httpStatus?: Record<string, never>;
                        /** @example The user was not found. */
                        message?: string;
                    };
                };
            };
        };
    };
    deleteBrandMiddleCategory: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example USER_NOT_FOUND */
                        code?: string;
                        /** @example null */
                        details?: Record<string, never>;
                        /** @example null */
                        httpStatus?: Record<string, never>;
                        /** @example The user was not found. */
                        message?: string;
                    };
                };
            };
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example USER_NOT_FOUND */
                        code?: string;
                        /** @example null */
                        details?: Record<string, never>;
                        /** @example null */
                        httpStatus?: Record<string, never>;
                        /** @example The user was not found. */
                        message?: string;
                    };
                };
            };
        };
    };
    updateBrandMiddleCategory: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BrandMiddleCategoryUpdateCommand"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": number;
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example USER_NOT_FOUND */
                        code?: string;
                        /** @example null */
                        details?: Record<string, never>;
                        /** @example null */
                        httpStatus?: Record<string, never>;
                        /** @example The user was not found. */
                        message?: string;
                    };
                };
            };
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example USER_NOT_FOUND */
                        code?: string;
                        /** @example null */
                        details?: Record<string, never>;
                        /** @example null */
                        httpStatus?: Record<string, never>;
                        /** @example The user was not found. */
                        message?: string;
                    };
                };
            };
        };
    };
    updateOesikupAdmin: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AdminUserDto.UpdateCommand"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example USER_NOT_FOUND */
                        code?: string;
                        /** @example null */
                        details?: Record<string, never>;
                        /** @example null */
                        httpStatus?: Record<string, never>;
                        /** @example The user was not found. */
                        message?: string;
                    };
                };
            };
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example USER_NOT_FOUND */
                        code?: string;
                        /** @example null */
                        details?: Record<string, never>;
                        /** @example null */
                        httpStatus?: Record<string, never>;
                        /** @example The user was not found. */
                        message?: string;
                    };
                };
            };
        };
    };
    getVersion: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
    findStoreManagers: {
        parameters: {
            query?: {
                estCd?: string;
                upperEstCd?: string;
                phone?: string;
                userName?: string;
                storeName?: string;
                brandName?: string;
                createUserId?: string;
                updateUserId?: string;
                page?: number;
                pageSize?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PageResponseStoreManagerQueryDto.Result"];
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example USER_NOT_FOUND */
                        code?: string;
                        /** @example null */
                        details?: Record<string, never>;
                        /** @example null */
                        httpStatus?: Record<string, never>;
                        /** @example The user was not found. */
                        message?: string;
                    };
                };
            };
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example USER_NOT_FOUND */
                        code?: string;
                        /** @example null */
                        details?: Record<string, never>;
                        /** @example null */
                        httpStatus?: Record<string, never>;
                        /** @example The user was not found. */
                        message?: string;
                    };
                };
            };
        };
    };
    getPathVariable: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VersionInfo"];
                };
            };
        };
    };
    getRequestParam: {
        parameters: {
            query: {
                name: string;
                age: number;
            };
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VersionInfo"];
                };
            };
        };
    };
    getSampleText: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                input: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string;
                };
            };
        };
    };
    healthCheck: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string;
                };
            };
        };
    };
    getConvertibleBrandMiddleCategories: {
        parameters: {
            query?: {
                keyword?: string;
                page?: number;
                pageSize?: number;
            };
            header?: never;
            path: {
                brandId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PageResponseConvertibleBrandDto.Result"];
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example USER_NOT_FOUND */
                        code?: string;
                        /** @example null */
                        details?: Record<string, never>;
                        /** @example null */
                        httpStatus?: Record<string, never>;
                        /** @example The user was not found. */
                        message?: string;
                    };
                };
            };
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example USER_NOT_FOUND */
                        code?: string;
                        /** @example null */
                        details?: Record<string, never>;
                        /** @example null */
                        httpStatus?: Record<string, never>;
                        /** @example The user was not found. */
                        message?: string;
                    };
                };
            };
        };
    };
    findConvertibleBrand: {
        parameters: {
            query?: {
                keyword?: string;
                largeGbn?: string;
                page?: number;
                pageSize?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PageResponseConvertibleBrandDto.Result"];
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example USER_NOT_FOUND */
                        code?: string;
                        /** @example null */
                        details?: Record<string, never>;
                        /** @example null */
                        httpStatus?: Record<string, never>;
                        /** @example The user was not found. */
                        message?: string;
                    };
                };
            };
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example USER_NOT_FOUND */
                        code?: string;
                        /** @example null */
                        details?: Record<string, never>;
                        /** @example null */
                        httpStatus?: Record<string, never>;
                        /** @example The user was not found. */
                        message?: string;
                    };
                };
            };
        };
    };
    getBrandAppLauncherIcon_1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AppIconDto.Result"];
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example USER_NOT_FOUND */
                        code?: string;
                        /** @example null */
                        details?: Record<string, never>;
                        /** @example null */
                        httpStatus?: Record<string, never>;
                        /** @example The user was not found. */
                        message?: string;
                    };
                };
            };
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example USER_NOT_FOUND */
                        code?: string;
                        /** @example null */
                        details?: Record<string, never>;
                        /** @example null */
                        httpStatus?: Record<string, never>;
                        /** @example The user was not found. */
                        message?: string;
                    };
                };
            };
        };
    };
    deleteAppLauncherIcon: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example USER_NOT_FOUND */
                        code?: string;
                        /** @example null */
                        details?: Record<string, never>;
                        /** @example null */
                        httpStatus?: Record<string, never>;
                        /** @example The user was not found. */
                        message?: string;
                    };
                };
            };
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example USER_NOT_FOUND */
                        code?: string;
                        /** @example null */
                        details?: Record<string, never>;
                        /** @example null */
                        httpStatus?: Record<string, never>;
                        /** @example The user was not found. */
                        message?: string;
                    };
                };
            };
        };
    };
    findOesikupAdminUser: {
        parameters: {
            query?: {
                keyword?: string;
                page?: number;
                pageSize?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PageResponseAdminUserDto.Result"];
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example USER_NOT_FOUND */
                        code?: string;
                        /** @example null */
                        details?: Record<string, never>;
                        /** @example null */
                        httpStatus?: Record<string, never>;
                        /** @example The user was not found. */
                        message?: string;
                    };
                };
            };
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example USER_NOT_FOUND */
                        code?: string;
                        /** @example null */
                        details?: Record<string, never>;
                        /** @example null */
                        httpStatus?: Record<string, never>;
                        /** @example The user was not found. */
                        message?: string;
                    };
                };
            };
        };
    };
    findFreshOnUser: {
        parameters: {
            query?: {
                keyword?: string;
                page?: number;
                pageSize?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PageResponseFreshOnUserDto.Result"];
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example USER_NOT_FOUND */
                        code?: string;
                        /** @example null */
                        details?: Record<string, never>;
                        /** @example null */
                        httpStatus?: Record<string, never>;
                        /** @example The user was not found. */
                        message?: string;
                    };
                };
            };
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example USER_NOT_FOUND */
                        code?: string;
                        /** @example null */
                        details?: Record<string, never>;
                        /** @example null */
                        httpStatus?: Record<string, never>;
                        /** @example The user was not found. */
                        message?: string;
                    };
                };
            };
        };
    };
}
